# Configuración del Servidor
server.port=8082
spring.application.name=servicio-quejas

# Conexión a la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/quejas_bancarias_db
spring.datasource.username=admin
spring.datasource.password=Admin123$

# Hibernate (Para crear las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración de Mailtrap API
mailtrap.api.token=47da79d8c1d2a60789cbd25a3024f392