server.port=8080
spring.application.name=puerta-enlace
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Configuracion nativa de CORS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].exposedHeaders=Authorization

# Mapa de Rutas para los Microservicios
spring.cloud.gateway.routes[0].id=servicio-auth
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=servicio-quejas
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/quejas/**